"""Reader and writer for the ``.inp`` file format used by the original
``MOC_Grid_BDE`` GUI.

The original code stored a sparse set of GUI radio-button states and numeric
fields in a whitespace-separated text file (see ``CMOC_GridDlg::OnFileOpen``
and ``OnFileSave`` in ``MOC_GridDlg.cpp``). This module preserves the exact
on-disk format so that ``.inp`` files generated by the Windows tool can be
loaded directly here, and vice-versa.

The first line holds the eleven boolean radio/check states in the same order
the C++ code wrote them. The remaining lines hold the numeric parameters
(also in the same order).
"""
from __future__ import annotations

import io
from dataclasses import dataclass, field
from pathlib import Path
from typing import Union

from ..common.constants import (
    AXI,
    CONE,
    EPS,
    EXITMACH,
    EXITPRESSURE,
    FIXEDEND,
    NOGEOM,
    NOTYPE,
    NOZZLELENGTH,
    PERFECT,
    RAO,
    TWOD,
)


@dataclass
class MOCInput:
    """Parsed contents of an MOC_Grid_BDE ``.inp`` file.

    Field names match the ``m_*`` member variables of ``CMOC_GridDlg``.

    Boolean radio/check fields (the eleven on line 1 of the file):

    ``throat``
        If true, ``pres_i`` / ``temp_i`` are throat *static* conditions and
        ``vel`` (ft/s) is the throat velocity. Otherwise they are stagnation
        conditions.
    ``perfect``, ``cone``, ``min_length``
        Nozzle-type radios. Exactly one is normally set.
    ``exit_mach``, ``end_point``, ``eps``, ``length``, ``p_exit``
        Design-parameter radios. Exactly one is normally set.
    ``axi``, ``two_d``
        Geometry radios. Exactly one is set.
    """

    # boolean fields (line 1)
    throat: bool = False
    perfect: bool = True
    exit_mach: bool = True
    axi: bool = True
    two_d: bool = False
    cone: bool = False
    min_length: bool = False
    end_point: bool = False
    eps: bool = False
    length: bool = False
    p_exit: bool = False

    # numeric fields (lines 2+)
    m_design: float = 4.0           # design exit Mach number
    n_c: int = 101                  # number of starting characteristics
    rwt_d: float = 1.0              # R_wall_downstream / R_throat
    mol_wt_i: float = 28.96         # molecular weight (lbm/lbm-mol)
    pres_i: float = 1000.0          # input pressure (psia) - total or throat
    temp_i: float = 530.0           # input temperature (R) - total or throat
    gamma_i: float = 1.4            # ratio of specific heats
    rwt_u: float = 1.0              # R_wall_upstream / R_throat
    d_t_limit: float = 0.5          # max delta-theta between wall pts (deg)
    p_amb: float = 0.0              # ambient pressure (psia)
    eps_value: float = 15.0         # design area ratio
    length_value: float = 5.03258   # design nozzle length / R*
    r_e: float = 1.6                # fixed endpoint radius / R*
    x_e: float = 4.308              # fixed endpoint axial location / R*
    n_rrc_above_bd: int = 100       # # of additional RRCs above point BD
    p_exit_value: float = 13.691    # design Ptotal / Pexit
    n_sl_i: int = 10                # # streamlines (radial)
    n_sl_j: int = 50                # # streamlines (axial)
    vel: float = 3022.0             # throat velocity (ft/s) when throat=True
    theta_bi: float = 25.0          # initial guess for ThetaB (deg)
    cone_angle: float = 15.0        # cone half-angle (deg) when cone=True

    # not in the file but useful at runtime
    print_mode: int = 0             # 0 = summary only, 1 = full output
    isp_ideal: float = 100.0        # ideal Isp used in Cfg computation

    # -- derived enum values --------------------------------------------------
    def nozzle_type(self) -> int:
        if self.perfect:
            return PERFECT
        if self.cone:
            return CONE
        if self.min_length:
            return RAO
        if self.end_point:
            return FIXEDEND
        return NOTYPE

    def nozzle_geom(self) -> int:
        if self.axi:
            return AXI
        if self.two_d:
            return TWOD
        return NOGEOM

    def design_param(self) -> int:
        if self.exit_mach:
            return EXITMACH
        if self.eps:
            return EPS
        if self.length:
            return NOZZLELENGTH
        if self.end_point:
            return EXITMACH  # end-point case stores params separately
        if self.p_exit:
            return EXITPRESSURE
        return EXITMACH

    def design_values(self) -> tuple[float, float]:
        """Return (primary, secondary) design values in the order the C++ code
        plugs into ``designValue[0]`` / ``designValue[1]``."""
        nt = self.nozzle_type()
        dp = self.design_param()
        if nt == FIXEDEND:
            # fixed-end: primary is x_e, secondary is r_e
            return self.x_e, self.r_e
        if dp == EXITMACH:
            primary = self.m_design
        elif dp == EPS:
            primary = self.eps_value
        elif dp == NOZZLELENGTH:
            primary = self.length_value
        elif dp == EXITPRESSURE:
            primary = self.p_exit_value
        else:
            primary = self.m_design
        secondary = self.cone_angle if nt == CONE else -99.9
        return primary, secondary


# --- file format -----------------------------------------------------------
_BOOLEAN_FIELDS = (
    "throat", "perfect", "exit_mach", "axi", "two_d", "cone",
    "min_length", "end_point", "eps", "length", "p_exit",
)


def _tokenize(text: str) -> list[str]:
    """Split on any whitespace, ignoring blank tokens."""
    return [tok for tok in text.replace("\t", " ").split() if tok]


def read_inp(path: Union[str, Path]) -> MOCInput:
    """Read an ``MOC_Grid_BDE`` ``.inp`` file from disk.

    Matches the format written by ``CMOC_GridDlg::OnFileSave`` in
    ``MOC_GridDlg.cpp``: line 1 has eleven 0/1 boolean fields, the remaining
    lines hold the numeric inputs in the same order they were emitted by the
    C++ code.
    """
    text = Path(path).read_text()
    tokens = _tokenize(text)
    if len(tokens) < 11 + 20:
        raise ValueError(
            f"{path}: file appears truncated -- expected at least 31 tokens, "
            f"got {len(tokens)}"
        )

    inp = MOCInput()
    # booleans
    for name, tok in zip(_BOOLEAN_FIELDS, tokens[:11]):
        setattr(inp, name, bool(int(tok)))
    # numerics, in the exact order written by the C++ ``OnFileSave``:
    #   m_mDesign, m_nC, m_RWTD, m_molWt_i,
    #   m_pres_i, m_temp_i, m_gamma_i, m_RWTU,
    #   m_dTLimit, m_pAmb,
    #   m_eps, m_length, m_rE, m_xE,
    #   m_nRRCAboveBD, m_pExit,
    #   m_nSLi, m_nSLj, m_vel, m_thetaBi,
    #   m_coneAngle
    nums = tokens[11:]
    inp.m_design       = float(nums[0])
    inp.n_c            = int(float(nums[1]))
    inp.rwt_d          = float(nums[2])
    inp.mol_wt_i       = float(nums[3])
    inp.pres_i         = float(nums[4])
    inp.temp_i         = float(nums[5])
    inp.gamma_i        = float(nums[6])
    inp.rwt_u          = float(nums[7])
    inp.d_t_limit      = float(nums[8])
    inp.p_amb          = float(nums[9])
    inp.eps_value      = float(nums[10])
    inp.length_value   = float(nums[11])
    inp.r_e            = float(nums[12])
    inp.x_e            = float(nums[13])
    inp.n_rrc_above_bd = int(float(nums[14]))
    inp.p_exit_value   = float(nums[15])
    inp.n_sl_i         = int(float(nums[16]))
    inp.n_sl_j         = int(float(nums[17]))
    inp.vel            = float(nums[18])
    inp.theta_bi       = float(nums[19])
    if len(nums) > 20:
        inp.cone_angle = float(nums[20])
    return inp


def write_inp(inp: MOCInput, path: Union[str, Path]) -> None:
    """Write an :class:`MOCInput` to disk in the legacy format."""
    buf = io.StringIO()
    bools = [str(int(getattr(inp, n))) for n in _BOOLEAN_FIELDS]
    buf.write("\t".join(bools) + "\n")
    buf.write(f"{inp.m_design}\t{inp.n_c}\t{inp.rwt_d}\t{inp.mol_wt_i}\n")
    buf.write(f"{inp.pres_i}\t{inp.temp_i}\t{inp.gamma_i}\t{inp.rwt_u}\n")
    buf.write(f"{inp.d_t_limit}\t{inp.p_amb}\n")
    buf.write(f"{inp.eps_value}\t{inp.length_value}\t{inp.r_e}\t{inp.x_e}\n")
    buf.write(f"{inp.n_rrc_above_bd}\t{inp.p_exit_value}\n")
    buf.write(f"{inp.n_sl_i}\t{inp.n_sl_j}\t{inp.vel}\t{inp.theta_bi}\n")
    buf.write(f"{inp.cone_angle}\n")
    Path(path).write_text(buf.getvalue())
